apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nmos
  name: nmos-cpp
  namespace: default
  resourceVersion: "8641"
  uid: 99945894-80e8-44a4-82a8-7f93b582c2a0
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    port: 8010
    protocol: TCP
    targetPort: 8010
  - name: port-2
    port: 8011
    protocol: TCP
    targetPort: 8011
  - name: port-3
    port: 11000
    protocol: TCP
    targetPort: 11000
  - name: port-4
    port: 11001
    protocol: TCP
    targetPort: 11001
  - name: port-5
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: port-6
    port: 5353
    protocol: UDP
    targetPort: 5353
  selector:
    app.kubernetes.io/name: nmos
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
